### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by ranocha** [MuMPlaCL/InductionEq#9]
We might want to discuss the usage of compiler warnings as in https://github.com/MuMPlaCL/InductionEq/blob/db5cb438d00096458d34e414cf8ecdf83e556c49/kernel/artificial_dissipation.cl#L170.
Why should one choice of artificial dissipation (i.e. none) be special? Additionally, OpenCL does not really give some help with warnings...

**Comment by Kostaszki** [comment]
Those are mostly relics from earlier implementation stages. If you are fine with it I would remove them.

**Comment by ranocha** [comment]
That's okay for me.
